### ISSUE TITLE
from tensorflow.contrib.seq2seq.python.ops.attention_wrapper import _compute_attention

### ISSUE THREAD

**Issue by buyanfangqi** [goodhamgupta/aon#1]
Hello, I download the aon and debug in pycharm, but the _compute_attentaion cannot find, 
I guess it is the version problem of  tf?

**Comment by goodhamgupta** [comment]
Hi @buyanfangqi,

I'm not sure I understand your problem. At what point are you not able to find the `_compute_attention` module? Is it when you're trying to run the `train.py` file?

**Comment by buyanfangqi** [comment]
Sorry, I didn't express my question clearly. 
The original  problem is following:
In the sync_attention_wrapper.py have "from tensorflow.contrib.seq2seq.python.ops.attention_wrapper import _compute_attention" ,but it say haven't the module of _compute_attention.

I solve the problem after upgrade the tf from 1.2 to 1.3.

Thanks!
